---
This script takes georeferenced Tomistoma schlegelii presence records sourced from; both published and unpublished datasets, 211 from Stuebing et al. (2006), 113 from Sideleau (2023), 36 from Dr Agata Staniewicz and 23 from The Global Biodiversity Information Facility (2023), with additional data from; museum specimen records, sightings, published journal articles and archival field expedition journals, and wrangles it for downstream analysis.
---

#load packages#
```{r }
library(readr)
library(tidyverse)
```


#Load data#
```{r }
data<-read.csv("C:/Users/student/OneDrive/Conservation, Evol, Ecol/Project Two/Tomistoma Distributions Reproducible Code/Tomistoma Distributions Reproducible Code/Tomistoma schlegelli locality data .csv")
```

#Limit columns#
```{r }
data<-select(data, 'Lat', 'Long', 'Extent', 'Date', 'Keep')
```


#Filter NAs out#
```{r }
data <- data %>%
      filter(trimws(Keep) != "N")
```

#Remove NAs from date#
```{r }
data <- data %>%
  filter(complete.cases(Date))
```


#Order date#
```{r }
data <- data %>%
arrange(Date)
```

#Remove rows with values greater than 50 in 'Extent' column, keeping NAs#
```{r }
df_filtered <- data[is.na(data$Extent) | data$Extent <= 50, ]
```

#Print the filtered data frame#
```{r }
data<-print(df_filtered)
sapply(data,class) 
nrow(df_filtered)
view(data)

```

#Write csv#
```{r }
write.csv(data, file = "locality_data", row.names = FALSE)
```

#Export the data frame using write_csv
```{r }
write_csv(data, "locality_data")
```



